# Generated by Django 5.1.3 on 2024-12-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file_location', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf_file_location', models.CharField(blank=True, max_length=255, null=True)),
                ('pass_policy_count', models.IntegerField()),
                ('fail_policy_count', models.IntegerField()),
                ('compliance_percentage', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_result',
                'ordering': ['-timestamp'],
            },
        ),
    ]
