# Generated by Django 5.1.3 on 2024-12-08 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auditresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersystemconfig',
            name='os_index',
            field=models.IntegerField(default=-1),
        ),
    ]
