# Generated by Django 5.1.3 on 2024-12-09 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_grouplist_grouppolicy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouppolicy',
            old_name='group_id',
            new_name='group',
        ),
    ]
